#pragma once

#include "StatusCode.hpp"

// informational response

#define HTTP_CONTINUE 100
#define HTTP_SWITCHING_PROTOCOLS 101
#define HTTP_PROCESSING 102
#define HTTP_EARLY_HINTS 103

// successful

#define HTTP_OK 200
#define HTTP_CREATED 201
#define HTTP_ACCEPTED 202
#define HTTP_NON_AUTHORITATIVE_INFORMATION 203
#define HTTP_NO_CONTENT 204
#define HTTP_RESET_CONTENT 205
#define HTTP_PARTIAL_CONTENT 206
#define HTTP_MULTI_STATUS 207
#define HTTP_ALREADY_REPORTED 208
#define HTTP_IM_USED 226

// redirection

#define HTTP_MULTIPLE_CHOICES 300
#define HTTP_MOVED_PERMANENTLY 301
#define HTTP_FOUND 302
#define HTTP_SEE_OTHER 303
#define HTTP_NOT_MODIFIED 304
#define HTTP_USE_PROXY 305
#define HTTP_TEMPORARY_REDIRECT 307
#define HTTP_PERMANENT_REDIRECT 308

// client error

#define HTTP_BAD_REQUEST 400
#define HTTP_UNAUTHORIZED 401
#define HTTP_PAYMENT_REQUIRED 402
#define HTTP_FORBIDDEN 403
#define HTTP_NOT_FOUND 404
#define HTTP_METHOD_NOT_ALLOWED 405
#define HTTP_NOT_ACCEPTABLE 406
#define HTTP_PROXY_AUTHENTICATION_REQUIRED 407
#define HTTP_REQUEST_TIMEOUT 408
#define HTTP_CONFLICT 409
#define HTTP_GONE 410
#define HTTP_LENGTH_REQUIRED 411
#define HTTP_PRECONDITION_FAILED 412
#define HTTP_PAYLOAD_TOO_LARGE 413
#define HTTP_URI_TOO_LONG 414
#define HTTP_UNSUPPORTED_MEDIA_TYPE 415
#define HTTP_RANGE_NOT_SATISFIABLE 416
#define HTTP_EXPECTATION_FAILED 417
#define HTTP_MISDIRECTED_REQUEST 421
#define HTTP_UNPROCESSABLE_ENTITY 422
#define HTTP_LOCKED 423
#define HTTP_FAILED_DEPENDENCY 424
#define HTTP_TOO_EARLY 425
#define HTTP_UPGRADE_REQUIRED 426
#define HTTP_PRECONDITIONS_REQUIRED 428
#define HTTP_TOO_MANY_REQUESTS 429
#define HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE 431
#define HTTP_UNAVAILABLE_FOR_LEGAL_REASONS 451

// server error

#define HTTP_INTERNAL_SERVER_ERROR 500
#define HTTP_NOT_IMPLEMENTED 501
#define HTTP_BAD_GATEWAY 502
#define HTTP_SERVICE_UNAVAILABLE 503
#define HTTP_GATEWAY_TIMEOUT 504
#define HTTP_VERSION_NOT_SUPPORTED 505
#define HTTP_VARIANT_ALSO_NEGOTIATES 506
#define HTTP_INSUFFICIENT_STORAGE 507
#define HTTP_LOOP_DETECTED 508
#define HTTP_NOT_EXTENDED 510
#define HTTP_NETWORK_AUTHENTICATION_REQUIRED 511

// other

#define HTTP_I_AM_A_TEAPOT 418

//
// Messages
//

// informational respo_MSG ""
#define HTTP_CONTINUE_MSG ""
#define HTTP_SWITCHING_PROTOCOLS_MSG ""
#define HTTP_PROCESSING_MSG ""
#define HTTP_EARLY_HINTS_MSG ""
// succes_MSG ""
#define HTTP_OK_MSG ""
#define HTTP_CREATED_MSG ""
#define HTTP_ACCEPTED_MSG ""
#define HTTP_NON_AUTHORITATIVE_INFORMATION_MSG ""
#define HTTP_NO_CONTENT_MSG ""
#define HTTP_RESET_CONTENT_MSG ""
#define HTTP_PARTIAL_CONTENT_MSG ""
#define HTTP_MULTI_STATUS_MSG ""
#define HTTP_ALREADY_REPORTED_MSG ""
#define HTTP_IM_USED_MSG ""
// redirec_MSG ""
#define HTTP_MULTIPLE_CHOICES_MSG ""
#define HTTP_MOVED_PERMANENTLY_MSG ""
#define HTTP_FOUND_MSG ""
#define HTTP_SEE_OTHER_MSG ""
#define HTTP_NOT_MODIFIED_MSG ""
#define HTTP_USE_PROXY_MSG ""
#define HTTP_TEMPORARY_REDIRECT_MSG ""
#define HTTP_PERMANENT_REDIRECT_MSG ""
// client e_MSG ""
#define HTTP_BAD_REQUEST_MSG ""
#define HTTP_UNAUTHORIZED_MSG ""
#define HTTP_PAYMENT_REQUIRED_MSG ""
#define HTTP_FORBIDDEN_MSG ""
#define HTTP_NOT_FOUND_MSG ""
#define HTTP_METHOD_NOT_ALLOWED_MSG ""
#define HTTP_NOT_ACCEPTABLE_MSG ""
#define HTTP_PROXY_AUTHENTICATION_REQUIRED_MSG ""
#define HTTP_REQUEST_TIMEOUT_MSG ""
#define HTTP_CONFLICT_MSG ""
#define HTTP_GONE_MSG ""
#define HTTP_LENGTH_REQUIRED_MSG ""
#define HTTP_PRECONDITION_FAILED_MSG ""
#define HTTP_PAYLOAD_TOO_LARGE_MSG ""
#define HTTP_URI_TOO_LONG_MSG ""
#define HTTP_UNSUPPORTED_MEDIA_TYPE_MSG ""
#define HTTP_RANGE_NOT_SATISFIABLE_MSG ""
#define HTTP_EXPECTATION_FAILED_MSG ""
#define HTTP_MISDIRECTED_REQUEST_MSG ""
#define HTTP_UNPROCESSABLE_ENTITY_MSG ""
#define HTTP_LOCKED_MSG ""
#define HTTP_FAILED_DEPENDENCY_MSG ""
#define HTTP_TOO_EARLY_MSG ""
#define HTTP_UPGRADE_REQUIRED_MSG ""
#define HTTP_PRECONDITIONS_REQUIRED_MSG ""
#define HTTP_TOO_MANY_REQUESTS_MSG ""
#define HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE_MSG ""
#define HTTP_UNAVAILABLE_FOR_LEGAL_REASONS_MSG ""

// server
#define HTTP_INTERNAL_SERVER_ERROR_MSG ""
#define HTTP_NOT_IMPLEMENTED_MSG ""
#define HTTP_BAD_GATEWAY_MSG ""
#define HTTP_SERVICE_UNAVAILABLE_MSG ""
#define HTTP_GATEWAY_TIMEOUT_MSG ""
#define HTTP_VERSION_NOT_SUPPORTED_MSG ""
#define HTTP_VARIANT_ALSO_NEGOTIATES_MSG ""
#define HTTP_INSUFFICIENT_STORAGE_MSG ""
#define HTTP_LOOP_DETECTED_MSG ""
#define HTTP_NOT_EXTENDED_MSG ""
#define HTTP_NETWORK_AUTHENTICATION_REQUIRED_MSG ""
// o_MSG ""
#define HTTP_I_AM_A_TEAPOT_MSG ""

//
// Global
//

extern http::StatusCode status_code;
